FITA/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/29 23:36
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @Software: PyCharm
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from extra_apps import xadmin
from manage_site.views import IndexView,ApplicationView,ContactView,ActJoinView
from django.conf.urls.static import static
from . import settings
#todo:全局404
urlpatterns = [
    path('admin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^application/$', ApplicationView.as_view(), name='application'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^act-join/(?P<act_id>\d+)/', ActJoinView.as_view(),name='act-join'),
    url('^users/', include('users.urls')),
    url(r'courses/', include('courses.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/6 1:14
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @File    : urls.py
# @Software: PyCharm

from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'(?P<user_id>\d+)/$', UserCenterView.as_view(), name='user_info'),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),
    url(r'^register/$', RegisterView.as_view(), name="register"),
    url(r'^forget/$', ForgetPasswordView.as_view(), name='forget'),
    url(r'^reset/(?P<active_code>.*)/$', ResetPasswordView.as_view(), name='reset'),
    url(r'^(?P<user_id>\d+)/changeImg', ImgChangeApi.as_view(), name='change_img')
]

users/models.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/29 23:36
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @Software: PyCharm

from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from FITA.settings import DEP_CHOICE,PROVINCE




class UserProfile(AbstractUser):
    gender = models.CharField(choices=(("Male", "男"), ("female", "女")), max_length=6, verbose_name='性别')
    address = models.CharField(choices=PROVINCE,max_length=5, default='wt', verbose_name='省份')
    email = models.EmailField(null=True, blank=True, verbose_name='邮箱')
    department = models.CharField(choices=DEP_CHOICE,default='z',verbose_name='学院',max_length=20)
    image = models.ImageField(upload_to="users/%Y/%m", default="/users/default.png", max_length=100,verbose_name='头像')
    is_member = models.BooleanField(default=False, verbose_name='是否成员')

    class Meta:
        verbose_name = " 用户信息"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.username


class EmailVerifyRecord(models.Model):
    code = models.CharField(max_length=20, verbose_name="验证码")
    email = models.EmailField(max_length=50, verbose_name="邮箱")
    send_type = models.CharField(choices=(("register", "注册"), ("forget", "找回密码")),
                                 max_length=10, verbose_name="验证码类型")
    send_time = models.DateTimeField(default=datetime.now, verbose_name="发送时间")

    class Meta:
        verbose_name = "邮箱验证码"
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}({1})'.format(self.code, self.email)


edu_situation = (
    (u'未填', u'未填'), (u'大一', u'大一'), (u'大二', u'大二'),
    (u'大三', u'大三'), (u'大四', u'大四'), (u'大五', u'大五'),
    (u'研一',u'研一'), (u'研二', u'研二'), (u'研三', u'研三')
)

class Teacher(models.Model):
    name = models.ForeignKey(UserProfile,verbose_name="负责人姓名", on_delete=models.CASCADE)

    photo = models.ImageField(upload_to='users/teachers/%Y/%m', verbose_name='负责人照片', default='/users/teacher/default.png')
    edu_bak = models.CharField(verbose_name='当前学历', choices=edu_situation, default=u'未填', max_length=50)
    teacher_info = models.CharField(max_length=200, verbose_name="个人信息")
    click_num = models.IntegerField(default=0, verbose_name="点击数")
    fav_nums = models.IntegerField(default=0, verbose_name="收藏数目")
    add_time = models.DateTimeField(default=datetime.now, verbose_name='注册时间')

    class Meta:
        verbose_name = "负责人"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name.username

users/views.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/29 23:36
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @Software: PyCharm

import json,base64
from django.shortcuts import render,redirect,HttpResponse,HttpResponseRedirect,reverse,Http404
from django.views.generic import *
from .form import *
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.hashers import make_password
from operations.models import UserCourse
from .models import UserProfile,EmailVerifyRecord
from .utils import send_my_email




class LoginView(View):
    '''登陆页面'''
    def get(self,requset):
        return render(requset,'users/login.html',{'LoginForm':LoginForm()})

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request,username = username, password=password)
            print(username,password)
            if user:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                err_msg = '用户账户或密码错误'
        else:
            err_msg = '输入有误，请重试'
        return render(request,'users/login.html',{'err_msg':err_msg,'LoginForm':LoginForm()})


class RegisterView(View):
    '''注册页面'''
    def get(self,requset):
        return render(requset,'users/register.html',{'RegisterForm': RegisterForm()})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            genger = form.cleaned_data['gender']
            username = form.cleaned_data['username']

            if UserProfile.objects.all().filter(email=email):
                err_msg = '邮箱已存在'
                return render(request,'users/register.html',locals())
            else:
                UserProfile.objects.create_user(username=username,
                                                email=email,
                                                password=password,
                                                gender=genger,)
                return HttpResponseRedirect(reverse('index'))
        else:
            form = RegisterForm(initial={
                'username':request.POST.get('username', ''),
                'email':request.POST.get('email', ''),
                'gender':request.POST.get('gender', '')
            })

            return render(request, 'users/register.html',{'err_msg': '两次密码不相同，请重新输入', 'RegisterForm': form})


class LogoutView(View):
    '''注销'''
    def get(self,request):
        logout(request)
        return HttpResponseRedirect(reverse('index'))


class UserCenterView(LoginRequiredMixin,View):
    '''个人中心页面'''
    def get(self, request, user_id):
        user_id = int(user_id)
        try:
            # 个人信息
            user_info = UserProfile.objects.get(id=user_id)
            # 加入的课程
            all_course = UserCourse.objects.filter(user_id=user_id)
            #表单预填充
            user_info_form = UserInfoForm(initial={
                'email':user_info.email,
                'address':user_info.address,
                'department':user_info.department,
                'gender':user_info.gender,
            })
        except Exception:
            pass
        return render(request, 'users/user_center.html', locals())

    def post(self, request,user_id):
        '''用户信息AJAX提交处理'''
        post_user = request.user
        target_user = UserProfile.objects.get(id=user_id)
        msg = {"status": "failure", "data": "-1"} #默认-1  没有权限操作

        #1.验证是否本人
        if(target_user == post_user) is not True:
            return HttpResponse(json.dumps(msg), content_type='application/json')

        #2.修改个人信息
        user_info_form = UserInfoForm(request.POST, request.FILES, instance=request.user)
        if user_info_form.is_valid():
            user_info_form.save()
            msg['data'] = 0 #0表示修改成功
            msg['status'] = 'success'
        else:
            msg['data'] = '1' # 1表示数据不符合规范
        return HttpResponse(json.dumps(msg), content_type='application/json')


class UserDetailView(DetailView):
    model = UserProfile
    context_object_name = 'user_info'
    template_name = 'users/user_info.html'


class ForgetPasswordView(View):
    def get(self, request):
        email_form = ForgetForm()
        return render(request, 'users/pwd_forget.html', locals())

    def post(self,request):
        email_form = ForgetForm(request.POST)
        if email_form.is_valid():
            email = request.POST.get('email', '')
            if send_my_email(email, 'forget'):
                return HttpResponse('{"status":"success", "data":"验证码已经发送，请注意查收"}', content_type='application/json')
        return HttpResponse('{"status":"failure", "data":"发送失败，请稍后再试"}', content_type='application/json')


class ResetPasswordView(View):
    def get(self, request, active_code):
        record = EmailVerifyRecord.objects.get(code=active_code)
        if record:
            email = record.email
            modify_form = ModifyPwdForm()
            return render(request, 'users/pwd_reset.html',locals())
        return render(request,'manage_site/index.html')

    def post(self, request, active_code):
        record = EmailVerifyRecord.objects.get(code=active_code)
        modify_forms = ModifyPwdForm(request.POST)
        if modify_forms.is_valid():
            pwd1 = request.POST.get("password1", "")
            pwd2 = request.POST.get("password2", "")
            email = record.email
            if pwd1 == pwd2:
                user = UserProfile.objects.get(email=email)
                user.password = make_password(pwd2)
                user.save()
                return HttpResponseRedirect(reverse('login'))
        msg = {'err_msg': '两次密码输入不一致'}
        modify_form = ModifyPwdForm()
        return render(request, "users/pwd_reset.html", locals())



class ImgChangeApi(LoginRequiredMixin,View):
    def post(self, request,user_id):
        img = request.FILES.get('user_img')
        request.user.image = img
        request.user.save()
        return HttpResponse('{"status":"success", "data":"修改成功"}', content_type='application/json')

users/templates/users/login.html
{% extends 'manage_site/base.html' %}
{% load static %}
{% block page_title %}
    登录
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

{% block body %}
      <section class="container a-join">
    <div class="box">
        <form class="form form-group" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{ LoginForm.as_p }}
            <button type="submit" class="btn btn-primary btn-block">登录</button>
        </form>
            <button class="btn btn-block btn-default"> <span>没有账号？<a href="{% url 'register' %}">立即注册</a></span></button>
        <button class="btn btn-block btn-default"><span><a href="{% url 'forget' %}">忘记密码？</a></span></button>
    </div>
      </section>
{% endblock %}

users/templates/users/pwd_forget.html
{% extends 'manage_site/base.html' %}
{% load static %}
{% block page_title %}
    密码重设
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

{% block body %}
 <style>
        .errorlist {
            color: red;
        }
    </style>
    <section class="container a-join">
    <div class="box">
        <form id="forget" method="post">
                    {% csrf_token %}
                    {{ email_form.non_field_errors }}
                    {% for field in email_form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    {% if err_msg %}
                        <p class="errorlist">{{ err_msg }}</p>
                    {% endif %}
                    <button id="f-btn" type="button" class="btn btn-primary btn-block" style="margin-top: 40px">发送验证码</button>
                </form>
    </div>
      </section>
       <script>
        {#修改个人信息#}
        $.ajaxSetup({
            data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
        });//切记django的ajax使用post需要加上这个参数 否则csrf验证过不了
        $("#f-btn").click(function () {
            $.ajax({
                type: "POST",
                url:'{% url 'forget' %}',
                data:$('#forget').serialize(),
                error: function(request) {
                 alert('服务器正忙，请稍后再试');
                },
                success: function(data) {
                    alert(data.data);
                    window.location.href = '/';
                }
             });
         });
        {#修改密码#}
   </script>


{% endblock %}

users/templates/users/pwd_reset.html
{% extends 'manage_site/base.html' %}
{% load static %}
{% block page_title %}
    密码重设
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

{% block body %}
 <style>
        .errorlist {
            color: red;
        }
    </style>
    <section class="container a-join">
    <div class="box">
        <form class="form" action="{% url 'reset' active_code %}" method="post">
                    {% csrf_token %}
                    {% for field in modify_form %}
                        {{ field.label_tag }}
                        {{ field }}
                        {{ field.errors }}
                        {% if field.help_text %}
                            <p class="help text-small text-muted">{{ field.help_text|safe }}</p>
                        {% endif %}
                    {% endfor %}
                    {% if err_msg %}
                    <p class="errorlist">{{ err_msg }}</p>
                    {% endif %}
                    <button type="submit" class="btn btn-primary btn-block">确认修改</button>
                </form>
    </div>
      </section>

{% endblock %}

users/templates/users/register.html
{% extends 'manage_site/base.html' %}
{% load static %}
{% block page_title %}
    注册
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

{% block body %}
 <style>
        .errorlist {
            color: red;
        }
    </style>
    <section class="container a-join">
    <div class="box">
        <form class="form form-group" action="{% url 'login' %}" method="post">
            {% csrf_token %}
            {{ RegisterForm.as_p }}
            <button type="submit" class="btn btn-primary btn-block">登录</button>
        </form>
            <button class="btn btn-block btn-default"> <span>没有账号？<a href="{% url 'register' %}">立即注册</a></span></button>
        <button class="btn btn-block btn-default"><span><a href="{% url 'forget' %}">忘记密码？</a></span></button>
    </div>
      </section>

{% endblock %}

users/templates/users/user_center.html
{% extends 'manage_site/base.html' %}
{% load static %}


{% block page_title %}
    个人中心
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'users/css/users.css' %}">
{% endblock %}

{% block js %}
    <script src="{% static 'users/js/users.js' %}"></script>
{% endblock %}

{% block body %}
    <!-- todo:message框框 -->
    <!-- 个人信息 -->
<section class="container">
<div class="user-info">
<div class="user-img ">
    <a href="" data-toggle="modal" data-target="#changeImg"><img src="{{ user_info.image.url }}" alt="用户头像" style="width:96px;height: 96px" class="img-circle"></a>
</div>
    <div class="user-tab ">
    <h3>{{ user_info.username }}</h3>
    <p>{% if user_info.is_member %}您是社团成员{% endif %}</p>
    <div class="line"></div>
    <p>邮箱：{{ user_info.email }}</p>
    <p>学院：{{ user_info.get_department_display }}</p>
    <p>省份：{{ user_info.get_address_display|default:'未填' }}</p>
    <p>性别：{{ user_info.get_gender_display|default:'未填' }}</p>
    {% if user.id == user_info.id %}
    <p><a href="{% url 'forget' %}" class="btn btn-default" role="button">修改密码</a>  <a href="" data-toggle="modal" data-target="#changeInfo" class="btn btn-default" role="button">修改个人信息</a></p>
        <!-- 个人信息弹出框 -->
        <div class="modal fade" id="changeInfo" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="changeInfo" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改个人信息</h4>
              </div>
              <div class="modal-body">
                  <form class="form-group" id="user-form">
                  {% csrf_token %}
                      {% for field in user_info_form %}
                          {{ field.label }}
                          {{ field }}
                          {{ field.help_text }}
                      {% endfor %}
                  </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                <button id="info-button" type="button" class="btn btn-primary">保存</button>
              </div>
            </div>
          </div>
        </div>
        <!-- 头像弹出框 -->
        <div class="modal fade" id="changeImg" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="changeInfo" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">修改头像</h4>
              </div>
              <div class="modal-body">
                <div class="hovertreecontainer">
                <div class="imageBox">
                    <div class="thumbBox"></div>
                    <div class="spinner" style="display: none">Loading...</div>
                </div>
                <div class="cropped"></div>
                </div>
              </div>
              <div class="modal-footer">
                  <button  type="button" class="btn btn-info" style="float: left;line-height: 14px">
                      <label for="upload-file">上传图像</label>
                  </button>
                  <input type="file" class="" name="upload-file" id="upload-file" style="display: none" />
                  <div class="btn-group" role="group" aria-label="Default button group">
                      <button type="button" id="btnZoomOut" class="btn btn-default ">缩小</button>
                      <button type="button" id="btnCrop" class="btn btn-default ">剪切</button>
                      <button type="button" id="btnZoomIn" class="btn btn-default ">放大</button>
    </div>
                <button type="button" class="btn btn-danger" data-dismiss="modal">关闭</button>
                <button id="img-button" type="button" class="btn btn-primary">保存</button>
              </div>
            </div>
          </div>

        </div>
<script>
{#修改个人信息#}
$.ajaxSetup({
    data:{csrfmiddlewaretoken:'{{ csrf_token }}'}
});//切记django的ajax使用post需要加上这个参数 否则csrf验证过不了
$("#info-button").click(function () {
    $.ajax({
        type: "POST",
        url:'{% url 'user_info' user_id %}',
        data:$('#user-form').serialize(),
        error: function(request) {
         alert('服务器正忙，请稍后再试');
        },
        success: function(data) {
             if(data.data == 1) {
                 alert('数据不符合规范，请重新输入');
             }
             if(data.data == 0){
                 alert('修改成功！');
                 window.location.href="{% url 'user_info' user_id %}";
             }
             if(data.data == -1){
                 alert('您没有操作权限');
             }
        }
     });
 });

//===================base64转为blob==================
function convertBase64UrlToBlob(urlData){

    var bytes=window.atob(urlData.split(',')[1]);        //去掉url的头，并转换为byte

    //处理异常,将ascii码小于0的转换为大于0
    var ab = new ArrayBuffer(bytes.length);
    var ia = new Uint8Array(ab);
    for (var i = 0; i < bytes.length; i++) {
        ia[i] = bytes.charCodeAt(i);
    }
    return new Blob( [ab] , {type : 'image/png'});
}




$("#img-button").click(function () {
    var f_img = convertBase64UrlToBlob($('#f-img')[0].src);
    var formData = new FormData();
    formData.append('user_img',f_img);
    formData.append('csrfmiddlewaretoken','{{ csrf_token }}');
    $.ajax({
        type: "POST",
        url:'{% url 'change_img' user_id %}',
        data:formData,
        processData : false,
        contentType : false,
        error: function() {
         alert('服务器正忙，请稍后再试');
        },
        success: function(data) {
            alert(data.data);
        }
     });
 });
</script>
<script>
$(function() {
	var options =
	{
		thumbBox: '.thumbBox',
		spinner: '.spinner',
		imgSrc: '{{ user_info.image.url }}'
	};
	var cropper = $('.imageBox').cropbox(options);
	$('#upload-file').on('change', function(){
		var reader = new FileReader();
		reader.onload = function(e) {
			options.imgSrc = e.target.result;
			cropper = $('.imageBox').cropbox(options);
		};
		reader.readAsDataURL(this.files[0]);
		this.files = [];
	});
	$('#btnCrop').on('click', function(){
		var img = cropper.getDataURL();
		$('.cropped').html('');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" id="f-img" style="width:64px;margin-top:4px;border-radius:64px;box-shadow:0px 0px 12px #7E7E7E;" ><p>64px*64px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:128px;margin-top:4px;border-radius:128px;box-shadow:0px 0px 12px #7E7E7E;"><p>128px*128px</p>');
		$('.cropped').append('<img src="'+img+'" align="absmiddle" style="width:180px;margin-top:4px;border-radius:180px;box-shadow:0px 0px 12px #7E7E7E;"><p>180px*180px</p>');
	});
	$('#btnZoomIn').on('click', function(){
		cropper.zoomIn();
	});
	$('#btnZoomOut').on('click', function(){
		cropper.zoomOut();
	})


    var img = cropper.getDataURL();
});
</script>


{% endif %}
</div>

</div>





</section>
    <!-- 二级导航 -->
<section class="container">
<div class="u-nav">
<ul class="nav nav-tabs">
  <li role="presentation" class="active"><a href="#">课程</a></li>
  <li role="presentation"><a href="#">社团活动</a></li>
  <li role="presentation"><a href="#">敬请期待</a></li>
</ul>
</div>
</section>
    <!-- 课程列表 -->
<section class="container course-list">
    <div class="row" style="min-height: 300px">
    {% if all_course %}
             {% for course in all_course %}
         <div class="courses-item col-sm-6 col-md-4 col-lg-4">
    <div class="thumbnail">
        <a href="{% url 'course_detail' course.course.id %}"><img src="{{ course.course.image.url }}" alt=""></a>
        <div class="caption">
        <h3>{{ course.course.name }}</h3>
        <p>已有{{ course.course.students }}人参与</p>
        <p>浏览{{ course.course.click_nums }}次</p>
        <p>{{ course.course.description }}</p>
      </div>
    </div>
  </div>
    {% endfor %}
    {% else %}
        <h4>您还没有报名任何活动</h4>
        <button class="btn-default btn-primary"><a href="{% url 'course_list' %}">随便逛逛</a></button>
    {% endif %}
    </div>
</section>
{% endblock %}


{% block aaa %}

<h2>注册的课程</h2>






{% endblock %}

users/templates/users/user_info.html
{% extends 'manage_site/base.html' %}

{% block body %}
    {{ user_info.username }}
    {{ user_info.image }}

{% endblock %}

{% block user_course %}
{% endblock %}