FITA/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/29 23:36
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @Software: PyCharm
from django.contrib import admin
from django.conf.urls import url,include
from django.urls import path
from extra_apps import xadmin
from manage_site.views import IndexView,ApplicationView,ContactView,ActJoinView
from django.conf.urls.static import static
from . import settings
#todo:全局404
urlpatterns = [
    path('admin/', xadmin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^application/$', ApplicationView.as_view(), name='application'),
    url(r'^contact/$', ContactView.as_view(), name='contact'),
    url(r'^act-join/(?P<act_id>\d+)/', ActJoinView.as_view(),name='act-join'),
    url('^users/', include('users.urls')),
    url(r'courses/', include('courses.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manage_site/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2018/7/16 22:55
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @File    : urls.py
# @Software: PyCharm


from django.views.static import serve
from django.conf.urls import url
from FITA.settings import MEDIA_ROOT
urlpatterns = [

]

manage_site/models.py
from django.db import models
from datetime import datetime
from courses.models import Course

class Banner(models.Model):
    '''主页轮播公告功能'''
    title = models.CharField(max_length=100, verbose_name="标题",default='未填')
    details = models.TextField(max_length=500,verbose_name='公告内容',default='未填')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "轮播公告"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.title


class IndexCourse(models.Model):
    '''主页展示的课程'''
    course_name = models.ForeignKey(Course,verbose_name='课程名称',on_delete=models.CASCADE)
    des = models.TextField(max_length=200,verbose_name='简单描述')
    img = models.ImageField(upload_to="manage_site/course/%Y/%m",max_length=200,verbose_name='课程LOGO')

    class Meta:
        verbose_name = "展示课程"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.course_name.name



class IndexImgShow(models.Model):
    '''主页精彩照片墙'''
    image = models.ImageField(upload_to='manage_site/img_show/%Y/%d',max_length=100,verbose_name='照片')
    image_name = models.CharField(max_length=20,verbose_name='照片名称',default='精彩瞬间')
    des = models.TextField(max_length=200,verbose_name='照片描述')
    is_shown = models.BooleanField(default=True,verbose_name='是否显示')

    class Meta:
        verbose_name = "照片墙"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.image_name


class IndexCoreMembers(models.Model):
    '''主页核心成员'''
    name = models.CharField(max_length=20,verbose_name='核心成员姓名')
    image = models.ImageField(upload_to='manage_site/member/%Y/%d',max_length=100,verbose_name='成员照片')
    postion = models.CharField(max_length=30,verbose_name='担任职位')
    des = models.TextField(max_length=200,verbose_name='简单描述')
    is_shown = models.BooleanField(default=True, verbose_name='是否显示')
    class Meta:
        verbose_name = "核心成员展示"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name







class Preview(models.Model):
    '''主页活动预告'''
    is_shown = models.BooleanField(default=True,verbose_name='首页显示')

    people = models.IntegerField(verbose_name='已报名人数',default=0)
    name = models.CharField(max_length=20, verbose_name='活动名称')
    des = models.TextField(max_length=200, verbose_name='简单描述')
    details = models.TextField(max_length=500,verbose_name='详细信息')
    add_time = models.DateTimeField(default=datetime.now, verbose_name="添加时间")

    class Meta:
        verbose_name = "活动预告"
        verbose_name_plural = verbose_name
        ordering = ['-add_time']

    def __str__(self):
        return self.name

courses/views.py
# -*- coding: utf-8 -*-
# @Time    : 2018/6/29 23:36
# @Author  : TrumanGu
# @Email   : 1227085585@qq.com
# @Software: PyCharm
from datetime import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render,HttpResponse
from django.views.generic import ListView,DetailView,View
from .models import Course,Teacher,Lesson
from django.contrib.auth.mixins import LoginRequiredMixin
from operations.models import UserCourse,CourseComments,UserFavourite,UserLesson
# Create your views here.

#TODO:添加搜索功能
class CourseList(View):
    def get(self,request):
        course_list = Course.objects.all()

        paginator = Paginator(course_list, 6)
        page = request.GET.get('page', 1)
        currentPage = int(page)
        try:
            print(page)
            course_list = paginator.page(page)
        except PageNotAnInteger:
            course_list = paginator.page(1)
        except EmptyPage:
            course_list = paginator.page(paginator.num_pages)
        return render(request, 'courses/courses.html', locals())



class CourseDetailView(View):
    def get(self, request, course_id):
        course_has_fav = False
        course_org_has_fav = False
        '''课程点击量+1'''
        course = Course.objects.get(id=int(course_id))
        course.click_nums += 1
        course.save()
        '''负责人点击量+1'''
        teacher = Teacher.objects.get(id=course.teacher.id)
        teacher.click_num += 1
        teacher.save()

        '''课程章节信息'''
        lesson_list_history = Lesson.objects.filter(course_id=course_id, start_time__lt=datetime.now())
        lesson_list_future = Lesson.objects.filter(course_id=course_id, start_time__gt=datetime.now())
        return render(request, 'courses/detail.html', locals())


class CourseJoin(LoginRequiredMixin, View):
    '''用户加入课程'''
    def post(self, request, course_id):
       try:
           if(UserCourse.objects.filter(user=request.user,course_id=course_id)):
               return HttpResponse('{"status":"failure", "data":"您已经加入过该课程了"}', content_type='application/json')
           user_course = UserCourse.objects.create(user=request.user,course_id=course_id)
           add_course = Course.objects.get(id=course_id)
           add_course.students += 1
           add_course.save()
       except Exception as e:
           print(e)
           return HttpResponse('{"status":"failure", "data":"加入失败，请稍后再试"}', content_type='application/json')
       return HttpResponse('{"status":"success", "data":"加入成功"}', content_type='application/json')


class LessonJoin(LoginRequiredMixin, View):
    '''用户报名线下活动'''
    def post(self, request, course_id):
        user_id = request.POST.get('user_id','')
        lesson_id = request.POST.get('lesson_id','')
        if UserLesson.objects.filter(user_id=user_id, lesson_id=lesson_id):
            return HttpResponse('{"status":"failure", "data":"您已经报名了"}', content_type='application/json')
        lesson_record = UserLesson.objects.create(user_id=user_id,lesson_id=lesson_id)
        target_lesson = Lesson.objects.get(id=lesson_id)
        target_lesson.stu_num += 1
        target_lesson.save()
        UserCourse.objects.get_or_create(user=request.user, course_id=course_id)

        return HttpResponse('{"status":"success", "data":"报名成功"}', content_type='application/json')

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

manage_site/templates/manage_site/activities.html
{% extends 'manage_site/base.html' %}
{% load staticfiles %}
{% block page_title %}活动报名{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'manage_site/css/activities.css' %}">
{% endblock %}
{% block body %}

    <section class="container a-join">
    <div class="box">
        <h1>{{ act.name }}</h1>
        <p>{{ act.details }}</p>
        <p style="text-align: center"><span class="glyphicon glyphicon-user"> 已有</span>{{ act.people }}人报名</p>
        <button class="btn btn-primary btn-block act-join">报名</button>
    </div>

    </section>
   <script>
     $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
        });
        $('.act-join').click(function () {
            $.ajax({
                url:'{% url 'act-join' act.id%}',
                type:'POST',
                data:{'act_id':{{ act.id }}},
                success: function(data) {alert(data.data);}
            })
        });
    </script>
{% endblock %}

manage_site/templates/manage_site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}FITA社团{% endblock %}</title>
    <link href="{% static 'bootstrap-3.3.7/less/bootstrap.css' %}" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'manage_site/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'manage_site/css/index.css' %}">
  {% block css %}
  {% endblock %}
      <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
      <script src="{% static 'jquery-3.3.1/jquery-3.3.1.min.js' %}"></script>

  </head>
  <body>
<!--navbar -->
<section class="container-fluid">
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static 'manage_site/LOGO/logo.png' %}" alt="Brand" height="60px" width="auto">
{#          TODO:制定上传model#}
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div id="nav-cloud" class="visible-lg"  style="left: 130px; background-image: url({% static 'manage_site/imgs/hover.png'%}) ;position: absolute;height: 80px;width: 80px "></div>
        <ul class="nav navbar-nav">
        <li class="nav-icon"><a href="{% url 'index' %}">社团主页 <span class="sr-only">(current)</span></a></li>
        <li class="nav-icon"><a class="cs" href="{% url 'course_list' %}">第二课堂</a></li>
        <li class="nav-icon"><a class="st"  href="javascript:void(0)">社团风采</a></li>
        <li class="nav-icon"><a class="pv" href="javascript:void(0)">活动预告</a></li>
        <li class="nav-icon"><a class="mb" href="javascript:void(0)">核心成员</a></li>
        <li class="nav-icon visible-lg"><a class="j" href="javascript:void(0)">加入社团</a></li>
        <li class="nav-icon visible-lg"><a class="ct" href="javascript:void(0)">联系我们</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
              <li><a href="{% url 'user_info' user.id %}">个人中心</a></li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><span class="caret"></span></a>
    <ul class="dropdown-menu">
            <li><a href="#">预约的活动</a></li>
            <li><a href="#">参与过的活动</a></li>
            <li><a href="#"></a></li>
            <li role="separator" class="divider"></li>
              <li><a href="{% url 'forget' %}">修改密码</a></li>
            <li><a href="{% url 'logout' %}">注销</a></li>
          </ul>
        </li>
              {% else %}
              <li><a href="{% url 'register' %}">注册</a></li>
            <li><a href="{% url 'login' %}">登录</a></li>
          {% endif %}
      </ul>
    </div>
  </div>
</nav>
</section>

<!--body -->
{% block big_slide %}
<section class="big-slide">
    <img src="{% static 'manage_site/imgs/slide.png' %}" style="height: 100%;width: 100%">
    <div class="page-title"><h2>{% block page_title %}页面标题{% endblock %}</h2> </div>
</section>
{% endblock %}
{% block body %}

{% endblock %}
<!--footer -->
<section class="container-fluid footer">
    <div class="container">
        <div class="row">
            <div class='hidden-xs col-lg-4 col-lg-4 col-md-4 col-sm-4'>
                <h3>我们的GitHub团队</h3>
                <p>The Team For Beginners Of Programming</p>
                <a href="https://github.com/orgs/SabreHawk-Studio/teams/beginner-reserve-team">
                    https://github.com/orgs/SabreHawk-Studio/teams/beginner-reserve-team
                </a>
                <div class="horizontal"></div>
                <p>Pixel Fight Developing Team</p>
                <a href="https://github.com/orgs/SabreHawk-Studio/teams/pixelfightteam">https://github.com/orgs/SabreHawk-Studio/teams/pixelfightteam</a>
                <div class="horizontal"></div>
                <p>Website Developing Team</p>
                <a href="https://github.com/orgs/SabreHawk-Studio/teams/webdevteam">https://github.com/orgs/SabreHawk-Studio/teams/webdevteam</a>
            </div>
            <div class='col-lg-4 col-lg-4 col-md-4 col-sm-4'>
                <h3>加入社团</h3>
                <p>FITA社团非常欢迎新人的加入 Lorem ipsum dolor sit amet, consectetur adipisicing elit. Adipisci esse fugiat ipsum nostrum officia placeat quis soluta, velit. Delectus deserunt eligendi placeat quos vero. Alias debitis dicta et similique sunt!</p>
                <form id="app-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_des">个人简介:</label>
                        <textarea name="des" cols="40" rows="4" class="form-control" placeholder="输入您的社团加入申请" required id="id_des"></textarea>
                    </div>
                    <button id="app-button" type="button" class="btn btn-primary">提交</button>
                </form>
            </div>
            <div class='hidden-xs col-lg-4 col-md-4 col-sm-4'>
                <h3>联系我们</h3>
                 <p>您的任何意见都能够帮助FITA社团前进！Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet distinctio itaque modi pariatur saepe sed suscipit. Commodi, consequatur cupiditate delectus ducimus ea, facilis officia, pariatur quaerat temporibus unde vel vitae?</p>
                 <form id="contact-form" enctype="multipart/form-data">
                     {% csrf_token%}
                     <div class="form-group">
                        <label for="id_des">内容:</label>
                        <textarea name="des" cols="40" rows="4" class="form-control" placeholder="在这输入您的宝贵意见" required id="id_des"></textarea>
                    </div>
                    <button id="contact-button" type="button" class="btn btn-primary">提交</button>
                </form>
            </div>
        </div>
    </div>
</section>
<script src="{% static 'bootstrap-3.3.7/dist/js/bootstrap.js' %}"></script>
<script src="{% static 'manage_site/js/index.js' %}"></script>
<script>
        $('#app-button').click(function () {
            {% if user.is_authenticated %}
           $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
        });
                $.ajax({
                url:'{% url 'application'%}',
                type:'POST',
                data:$('#app-form').serialize(),
                success: function(data) {
                    alert(data.data)
                }
            });
                {% else %}
                alert('您必须先登录');
            {% endif %}

        });
    $('#contact-button').click(function () {
        {% if user.is_authenticated %}
             $.ajaxSetup({
        data: {csrfmiddlewaretoken: '{{ csrf_token }}' }
    });

             $.ajax({
            url:'{% url 'contact'%}',
            type:'POST',
            data:$('#contact-form').serialize(),
            success: function(data) {
                alert(data.data)
            }
        });
        {% else %}
           alert('您必须先登录');
        {% endif %}

    });
</script>
  {% block js %}
      <!-- 锚点滚动 -->
      <script>
      $(function () {
          var courseOffset = $('.courses').offset().top;
          var showTimeOffset = $('.show-time').offset().top;
          var previewOffset = $('.preview').offset().top;
          var membersOffset = $('.member-title').offset().top;
          
          $('a.pv').click(function () {
              $('html,body').animate({scrollTop:previewOffset},500)
          });
          $('a.mb').click(function () {
              $('html,body').animate({scrollTop:membersOffset},500)
          });
          $('a.st').click(function () {
              $('html,body').animate({scrollTop:showTimeOffset},500)
          });
          $('a.j').click(function () {
              $('html,body').animate({scrollTop:membersOffset},500)
          });
          $('a.ct').click(function () {
              $('html,body').animate({scrollTop:membersOffset},500)
          });


      })
      </script>
  {% endblock %}
  </body>
</html>